[package]
name = "bergamot"
version = "0.1.0"
authors = ["toshokan <toshokan@shojigate.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xcb = "^0.9"
cairo-rs = { version = "^0.9", features = ["xcb"] }
cairo-sys-rs = "^0.10"

